config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ShoppingCart::Engine, at: '/', as: 'cart'
  root 'home#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }

  resources :books, only: %i[show index]
  get 'catalog', to: 'books#index'
  resources :reviews, only: :create
  resources :images, only: %i[new create show]
  get 'users', to: 'users#index'
  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'patch'
end

app/models/user.rb
# This User model
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_one :billing_address, class_name: 'ShoppingCart::ShippingAddress', dependent: :destroy
  has_one :shipping_address, class_name: 'ShoppingCart::ShippingAddress', dependent: :destroy
  has_many :orders, class_name: 'ShoppingCart::Order'
  has_many :reviews

  attr_accessor :skip_password
  validates :email, format: { with: /\A[^-.]\w+[-.]?(\w+[-!#$%&'*+\/=?^_`{|}~.]\w+)*[^-]@([\w\d]+)\.([\w\d]+)\z/ }
  validates :password, length: { minimum: 8 }, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)\S{8,}\z/ }, unless: :skip_password


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      auth_info = auth.info
      user.email = auth_info.email
      user.password = Devise.friendly_token[0, 20]
      split_name = auth_info.name.split(' ')
      user.first_name = split_name[0]
      user.last_name = split_name[1]
      user.image = auth_info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def admin?
    self.role == 'admin'
  end

  rails_admin do
    visible false
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# This controller for Users::OmniauthCallbacksController
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    req_env = request.env['omniauth.auth']
    @user = User.from_omniauth(req_env)

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = req_env
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
    UserMailer.confirmation_mail(params[:user][:email], params[:user][:password]).deliver_now if current_user.present?
  end

  def after_sign_up_path_for(_resource)
    return cart.checkout_step_path(:address) if session[:checkout] == 'checkout'
    root_path
  end
end

app/controllers/users/sessions_controller.rb
# This controller for Users::SessionsController
class Users::SessionsController < Devise::SessionsController
  def create
    auth = request.env['omniauth.auth']
    user = User.where(provider: auth['provider'],
                      uid: auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @this_user = current_user
  end

  def update
    change_email if params[:type] == 'change_email'
    change_pwd if params[:type] == 'change_pwd'
  end

  private

  def change_email
    current_user.skip_password = true
    current_user.update(params_email)
    render :index, this_user: @current_user.errors
  end

  def change_pwd
    current_user.update_with_password(params_pwd)
    render :index, this_user: current_user.errors
  end

  def params_pwd
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def params_email
    params.permit(:email)
  end
end

app/views/users/_change_email.haml
%p.in-gold-500.font-18.mb-25= t('change_email.title')
= form_for this_user, url: settings_privacy_path, class: "general-form-md" do |f|
  = f.hidden_field nil, name: :type, value: :change_email
  .form-group.mb-35{ class: ("has-error" unless this_user.errors[:email].empty?) }
    %label.control-label.input-label{for: "email"}= t('change_email.lable_email')
    = f.email_field :email, name: :email, class: "form-control", placeholder: t('change_email.enter_email')
    - unless this_user.errors[:email].empty?
      %span.help-block= this_user.errors[:email][0]
  .general-text-align
    %button.btn.btn-default.mb-35= t('button.save')

app/views/users/_change_password.haml
%p.in-gold-500.font-18.mb-25= t('change_pass.title')
= form_for current_user, url: settings_privacy_path, class: "general-form-md divider-lg-bottom pb-25" do |f|
  .form-group.mb-30{ class: ("has-error" unless current_user.errors[:current_password].empty?) }
    = f.hidden_field nil, name: :type, value: :change_pwd
    = f.label :current_password, t('change_pass.old_pwd'), class: 'control-label input-label'
    = f.password_field :current_password, placeholder: t('change_pass.old_pwd'), class: "form-control"
    - unless current_user.errors[:current_password].empty?
      %span.help-block= current_user.errors[:current_password][0]
  .form-group.mb-30{ class: ("has-error" unless current_user.errors[:password].empty?) }
    = f.label :password, t('change_pass.new_pwd'), class: 'control-label input-label'
    = f.password_field :password, placeholder: t('change_pass.new_pwd'), class: "form-control"
    - unless current_user.errors[:password].empty?
      %span.help-block= current_user.errors[:password][0]
  .form-group.mb-30{ class: ("has-error" unless current_user.errors[:password_confirmation].empty?) }
    = f.label :password_confirmation, t('change_pass.conf_pwd'), class: 'control-label input-label'
    = f.password_field :password_confirmation, placeholder: t('change_pass.conf_pwd'), class: "form-control"
    - unless current_user.errors[:password_confirmation].empty?
      %span.help-block= current_user.errors[:password_confirmation][0]
  .general-text-align
    %button.btn.btn-default.mb-35= t('button.save')

app/views/users/_remove_account.haml
%p.in-gold-500.font-18.mb-25= t('remove_account.title')
%form
  .general-settings-btn
    %button.btn.disabled.mb-20= t('remove_account.button')
  .form-group.checkbox.general-settings-checkbox
    %label.checkbox-label
      %input.checkbox-input{type: "checkbox", hidden: "true"}
      %span.checkbox-icon
        %i.fa.fa-check
      %span.checkbox-text= t('remove_account.confirm')

app/views/users/index.haml
%main.container
  %h1.general-title-margin= t('settings.title')
  %ul.nav.clearfix.mb-20{role: "tablist"}
    %li.tab-item{role: "presentation"}
      %a.tab-link{href: cart.settings_address_path }= t('settings.address')
    %li.tab-item.active{role: "presentation"}
      %a.tab-link{href: settings_privacy_path }= t('settings.privacy')
  .tab-content
    #privacy.tab-pane.fade.in.active{role: "tabpanel"}
      .row.mb-60
        .col-sm-5
          = render 'change_email', this_user: @current_user
        .col-sm-5.col-sm-offset-1
          = render 'change_password'
        .col-sm-12
          = render 'remove_account'