config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ShoppingCart::Engine, at: '/', as: 'cart'
  root 'home#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }

  resources :books, only: %i[show index]
  get 'catalog', to: 'books#index'
  resources :reviews, only: :create
  resources :images, only: %i[new create show]
  get 'users', to: 'users#index'
  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'patch'
end

app/controllers/home_controller.rb
# This controller for HomeController
class HomeController < ApplicationController
  def home
    @latests = Book.author.order_id_desc.limit(3)
    @bestsellers = Category.join_tables.distinct_category.filter_status.group_cat_name_book.order_total
  end
end

app/views/home/_best_sellers.haml
-# bestsellers.each do |best|
  = render 'layouts/book_lite', best: Book.find(best.book_id)

app/views/home/_carousel.haml
.row
  .col-sm-5
    .general-img-wrap
      = image_tag number_image(book, 0), alt: 'book-img', class: 'img-shadow general-thumbnail-img'
  .col-sm-7
    .mb-60
      %h1= book.name
      %p.lead= book.description
      %p.lead.small= book.authors.map{ |author| author.name}.join(", ")
      .general-align
        = button_to t("button.buy_now"), cart.order_items_path, params: {order_item: {quantity: 1, product_id: book.id}}, method: :post, remote: true, class: 'btn btn-primary'

app/views/home/home.haml
%main.container
  #slider.carousel.slide{'data-ride': "carousel"}
    %ol.carousel-indicators
      - @latests.count.times do |ind|
        %li{'data-target': "#slider", 'data-slide-to': ind}
    .carousel-inner{role: "listbox"}
      - @latests.each_with_index do |book, index|
        -if index == 0
          .item.active
            = render "home/carousel", book: book
        - else
          .item
            = render "home/carousel", book: book
    %a.left.carousel-control{href: "#slider", role: "button", 'data-slide': "prev"}
      %span.icon-prev{'aria-hidden': "true"}
      %span.sr-only Previous
    %a.right.carousel-control{href: "#slider", role: "button", 'data-slide': "next"}
      %span.icon-next{'aria-hidden': "true"}
      %span.sr-only Next
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t("title.welcome")
    .mb-res-50
      %p= t("text.home_members")
      = link_to t("button.start"), catalog_path(), class: "btn btn-default"
  .mb-35
    %h3=t ("text_helpers.best_sellers")
    .row
      = render "home/best_sellers", bestsellers: @bestsellers