config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ShoppingCart::Engine, at: '/', as: 'cart'
  root 'home#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }

  resources :books, only: %i[show index]
  get 'catalog', to: 'books#index'
  resources :reviews, only: :create
  resources :images, only: %i[new create show]
  get 'users', to: 'users#index'
  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'patch'
end

app/models/book.rb
# This Book
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  belongs_to :category
  has_many :order_items, class_name: 'ShoppingCart::OrderItem', foreign_key: :product_id
  has_many :orders, through: :order_items, class_name: 'ShoppingCart::Order'
  has_many :reviews
  has_many :images, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2, maximum: 150 }
  validates :price, presence: true, numericality: { greater_than: 1 }
  validates :description, presence: true, length: { minimum: 2, maximum: 2500 }
  validates :height, presence: true, numericality: { only_float: true, greater_than: 1 }
  validates :weight, presence: true, numericality: { only_float: true, greater_than: 1 }
  validates :depth, presence: true, numericality: { only_float: true, greater_than: 1 }
  validates :material, presence: true, length: { minimum: 2, maximum: 50 }
  validates :category_id, presence: true

  scope :author, -> { includes(:authors) }
  scope :category, -> { includes(:category) }
  scope :order_id_desc, -> { order('id desc') }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  include Sort

  before_action :list_catalog, only: [:index]
  def index
    @category ||= if param_category[:category]
                    Category.find_by(id: param_category[:category])
                  else
                    Category.all
                  end

    @count_book_in_category = count_book_in_category
    respond_to do |format|
      format.html
      format.js { render layout: false, location: catalog_path(@catalog_list) }
    end
  end

  def show
    @book = Book.find(params[:id])
    @order_item = current_order.order_items.new
  end

  private

  def param_category
    params.permit(:category)
  end
end

app/views/books/_catalog_list.haml
- catalog_list.in_groups_of(4).each do |group|
  .row
    - group.each do |best|
      = render 'layouts/book_lite', best: best if best.present?
.text-center
  = link_to t('button.view_more'), (path_to_next_page catalog_list), class: 'btn btn-primary', id: 'view_more', :remote => true unless catalog_list.last_page?

app/views/books/_filters.haml
%ul.dropdown-menu
  %li
    %a{href: catalog_path(category: category, sort: :newest)}= t("filters.newest_first")
  %li
    %a{href: catalog_path(category: category, sort: :popular)}= t("filters.pop_first")
  %li
    %a{href: catalog_path(category: category, sort: :price_low)}= t("filters.price_l")
  %li
    %a{href: catalog_path(category: category, sort: :price_hi)}= t("filters.price_h")

app/views/books/_new_review.haml
%h3.in-gold-500.mb-25= t("review.new-review")
.general-message-wrap.divider-lg
= form_for Review.new, url: reviews_path do |f|
  .ml-70
    %div
      .max-240
        .general-message-name= "#{current_user.email}"
  = f.hidden_field :book_id, value: book.id
  = f.label t('review.title')
  %br
  = f.text_area :comment, cols: 5, rows: 5, class: 'form-control'
  %br
  %button.btn.center-block.mb-20= t('button.save_continue')

app/views/books/_review.haml
%h3.in-gold-500.mb-25= t("review.title")
- reviews.each do |rev|
  .general-message-wrap.divider-lg
    .clearfix
      %img.img-circle.logo-size.inlide-block.pull-left{src: "https://www.smashingmagazine.com/wp-content/uploads/2015/09/smashing-book-5-2-large.jpg"}
      .ml-70
        %div
          .general-message-date.hidden-xs= rev.created_at.strftime("%m/%d/%Y")
          .max-240
            .general-message-verified Verified Reviewer
            .general-message-name= rev.user.email
        .mb-15
          %i.fa.fa-star.rate-star
          %i.fa.fa-star.rate-star
          %i.fa.fa-star.rate-star
          %i.fa.fa-star.rate-star
          %i.fa.fa-star.rate-star
        %p= rev.comment

app/views/books/index.haml
%main.container
  %h1.general-title-margin= t("title.catalog")
  .hidden-xs.clearfix
    .dropdowns.pull-right
      .dropdown.width-240
        %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
          = t("filters.newest_first")
          %i.fa.fa-angle-down.dropdown-icon.pull-right
        = render 'filters', category: @category
    %ul.list-inline.pt-10.mb-25.mr-240
      %li.mr-35
        %a.filter-link{href: catalog_path()}
          = t("text_helpers.all")
          %span.badge.general-badge= @books.count
      - @count_book_in_category.each do |count_cat|
        %li.mr-35
        = link_to  catalog_path(category: count_cat[0][1]), class: "filter-link #{active_category(count_cat[0][1])}" do
          = count_cat[0][0]
          %span.badge.general-badge= count_cat[1]
  .dropdowns.mb-25.visible-xs
    %p.lead.small.mb-10=t("filters.filter_by_cat")
    .dropdown
      %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        = t("filters.newest_first")
        %i.fa.fa-angle-down.dropdown-icon.pull-right
      = render 'filters', category: @category
    %p.lead.small.mb-10= t("text_helpers.sort_by")
    .dropdown
      %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
        = t("filters.newest_first")
        %i.fa.fa-angle-down.dropdown-icon.pull-right
      = render 'filters', category: @category
  .mb-120{id: "list_catalog"}
    = render 'catalog_list', catalog_list: @catalog_list

app/views/books/index.js.erb
if ($("#view_more").length) $("#view_more").remove();

$('#list_catalog .row:last').after('<%= j(render "/books/catalog_list", catalog_list: @catalog_list) %>');

app/views/books/show.haml
%main.container
  %a.general-back-link{href: "#"}
    %i.fa.fa-long-arrow-left.mr-15
    =link_to t("button.back_result"), :back, class: 'in-gold-500 mb-20'
  .row
    .col-sm-6
      .product-gallery
        .mb-20
          = image_tag number_image(@book, 0), alt: 'design-book', class: 'img-responsive'
        - if @book.images.count > 1
          .images.clearfix
            - for i in 1..3
              - unless @book.images[i].nil?
                %a.img-link{href: "#"}
                  = image_tag number_image(@book, i), alt: 'design-book'
    .col-sm-6
      %h1.mt-res-0= @book.name
      %p.lead.small= @book.authors.map{ |author| author.name}.join(", ")
      = form_for @order_item, url: cart.order_items_path, remote: true, authenticity_token: true do |f|
        .row
          .col-xs-12.col-md-4
            %p.h1.in-gold-500.mt-10= "€ #{@book.price}"
          .col-xs-5.col-md-3
            .input-group.general-position
              %a.input-link{href: "#"}
                %i.fa.fa-minus.line-height-40
              = f.text_field :quantity, class: "form-control quantity-input", value: 1, min: 1
              %a.input-link{href: "#"}
                %i.fa.fa-plus.line-height-40
          .col-xs-7.col-md-5
            = f.hidden_field :product_id, value: @book.id
            = f.submit t("button.add_to_cart"), class: "btn btn-default pull-right general-position"

      .general-info-wrap.divider-lg
        %p= t("text_helpers.description")
        %p.lead.small.line-height-2
          = truncate(@book.description, length: 100)
          = link_to '... ' + t("button.read_more"), '', class: "in-gold-500 ml-10", id: "show_full"
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left= t("text_helpers.y_publ")
          %p.lead.small.pull-right= @book.public_y.strftime("%Y")
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left= t("text_helpers.dimensions")
          %p.lead.small.pull-right= "H: #{@book.height} &quot; x W: #{@book.weight} &quot; x D: #{@book.depth} &quot;".html_safe
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left= t("text_helpers.materials")
          %p.lead.small.pull-right= @book.material
  .mb-80
    - if @book.reviews.processed.count > 0
      = render 'review', reviews: @book.reviews.processed
    - if current_user.present?
      = render 'new_review', book: @book
:javascript
  $(document).ready(function() {
    $('#show_full').click(function(e) {
      e.preventDefault()
      $(this).parent().html('#{escape_javascript @book.description}')
    })
  });