config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ShoppingCart::Engine, at: '/', as: 'cart'
  root 'home#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }

  resources :books, only: %i[show index]
  get 'catalog', to: 'books#index'
  resources :reviews, only: :create
  resources :images, only: %i[new create show]
  get 'users', to: 'users#index'
  match 'settings/privacy', to: 'users#index', via: 'get'
  match 'settings/privacy', to: 'users#update', via: 'patch'
end

app/views/shopping_cart/carts/_head_quantity_cart.js.erb
if ($(".shop-quantity").length)$('.shop-quantity').html('<%=qty %>');
else $('.shop-icon').html('<span class="shop-quantity"><%=qty %></span>');

app/views/shopping_cart/carts/_line_product.haml
- order_items.each do |item|
  %tr
    %td
      .general-img-wrap-table
        = image_tag number_image(item.product, 0), alt: 'book-img', class: 'cart-img-shadow pull-left'
    %td
      %p.title= item.product.name
    %td
      %span.font-16.in-gold-500= "€ #{item.price}"
    %td
      .input-group
        = link_to decrease_order_item_path(item, authenticity_token: form_authenticity_token), method: :put, class: "input-link" do
          %i.fa.fa-minus.line-heaght-40
        %input.form-control.quantity-input{type: "text", value: item.quantity}
        = link_to increase_order_item_path(item, authenticity_token: form_authenticity_token), method: :put, class: "input-link" do
          %i.fa.fa-plus.line-heaght-40
    %td
      %span.font-16.in-gold-500= "€ #{item.item_total_price}"
    %td
      = button_to order_item_path(item), { method: :delete, class: "close general-cart-close", 'aria-label': "Close" } do
        %span{'aria-hidden': "true"} &times;

app/views/shopping_cart/carts/_line_product_xs.haml
- order_items.each do |item|
  .general-cart-item.divider-lg-bottom
    %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
      %span{'aria-hidden': "true"} &times;
    .general-img-wrap-table
      %img.cart-img-shadow{src: "http://jonathantweedy.com/resources/thumbs/SmashingBook5ResponsiveWebDesign.jpg", alt: "design-book"}
    %p.title= item.product.name
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= "€ #{item.price}"
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          .input-group
            %a.input-link{href: "#"}
              %i.fa.fa-minus.line-heaght-40
            %input.form-control.quantity-input{type: "text", value: item.quantity}
            %a.input-link{href: "#"}
              %i.fa.fa-plus.line-heaght-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500= "€ #{item.price*item.quantity}"

app/views/shopping_cart/carts/_order_summary.haml
%table.general-summary-table.general-summary-table-right.general-text-right
  %tr
    %td
      %p.font-16= t("cart.subtotal")
    %td
      %p.font-16= "€ #{order.total_price}"
  %tr
    %td
      %p.font-16= t("cart.coupon")
    %td
      %p.font-16= "€ #{order.discount}"
  %tr
    %td
      %strong.font-18= t("cart.total")
    %td
      %strong.font-18= "€ #{order.order_total}"

app/views/shopping_cart/carts/show.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart

  - if @order_items.any?
    .visible-xs
      = render 'line_product_xs', order_items: @order_items
    .hidden-xs
      %table.table.table-hover
        %tr.no-hover
          %th.col-pic.pl-0
            %span.in-grey-600 Product
          %th.col-title
          %th.col-price
            %span.in-grey-600 Price
          %th.col-quantity
            %span.in-grey-600 Quantity
          %th.col-total
            %span.in-grey-600 SubTotal
          %th.col-close
        = render 'line_product', order_items: @order_items
    .general-order-wrap
      .row
        = form_for cart_path(), method: :put do |f|
          .col-sm-4
            .input-group.general-input-group{ class: ("has-error" unless notice.blank?) }
              %label.input-label Enter Your Coupon Code
              = f.text_field nil, name: :coupon, class: "form-control mb-30", placeholder: "Enter Your Coupon Code "
              - unless notice.blank?
                %span.help-block= notice
              %div
                %button.btn.btn-primary.mr-5.mb-15.visible-xs-inline-block Apply Coupon
                %button.btn.btn-primary.mb-15.res-block Update cart
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18 Order Summary
            = render 'order_summary', order: current_order
            = button_to "Checkout", checkout_step_path(:address), method: :get, class: "btn btn-default mb-20 visible-xs-inline-block"
    = button_to "Checkout", checkout_step_path(:address), method: :get, class: "btn btn-default mb-20 hidden-xs center-block"
  - else
    %h1= t('cart.empty')